baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'cPanel elevate documentation'
theme = "cptheme"
#theme = "ananke"

sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "Elevate"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Forums"
    url = "https://forums.cpanel.net/"
    weight = 2
  
  [[menu.main]]
    name = "Support Ticket"
    url = "https://tickets.cpanel.net/review/login.cgi"
    weight = 3

##
## left menu
##
  [[menu.left]]
    name = "Introduction"
    url = "#introduction"
    weight = 1

  [[menu.left]]
    name = "Download"
    url = "#download-the-elevate-script"
    weight = 2

  [[menu.left]]
    name = "Usage"
    url = "#usage"
    weight = 3

  [[menu.left]]
    name = "Risks"
    url = "#risks"
    weight = 4

  [[menu.left]]
    name = "Copyright"
    url = "#copyright"
    weight = 5
