name: website

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod      
    - name: add timestamp
      working-directory: ./docs-website-src
      run: |
        date >> content/_index.md
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.2'

    - name: Build
      working-directory: ./docs-website-src
      run: |
        hugo -D

    - name: check
      run: |
        pwd
        cat docs/index.html
        git diff
    # - name: push
    #   uses: github-actions-x/commit@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     push_branch: 'master'
    #     commit_message: 'publish'