name: website

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: chdir
      working-directory: ./docs-website-src
      run: |
        cd docs-website-src
        date >> content/_index.md
    - name: build
      working-directory: ./docs-website-src
      uses: github-actions-x/hugo@master
    - name: check
      run: |
        pwd
        cat docs/index.html
        git diff
    # - name: push
    #   uses: github-actions-x/commit@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     push_branch: 'master'
    #     commit_message: 'publish'